/* ===== 站点数据（主页与详情页共用） ===== */

const PROFILE = {
  name: "Turdy",
  cnName: "张真",
  greeting: "你好，我是",
  roles: ["全栈开发者", "工具打造者", "独立游戏开发", "终身学习者", "好奇心驱动 ✨"],
  github: "https://github.com/Litrudy",
  githubHandle: "@Litrudy",
};

const SKILLS = [
  { icon: "🐍", name: "Python / FastAPI", level: 90 },
  { icon: "🎨", name: "HTML / CSS / JS", level: 88 },
  { icon: "🌐", name: "TypeScript / React", level: 80 },
  { icon: "🤖", name: "Kotlin / Jetpack Compose", level: 76 },
  { icon: "🪟", name: "PySide6 / Desktop Apps", level: 75 },
  { icon: "🗄️", name: "SQLite / SQLAlchemy", level: 74 },
  { icon: "🎮", name: "Godot / GDScript", level: 72 },
  { icon: "▲", name: "Next.js", level: 68 },
];

/* 每个项目：homepage 用 emoji/title/summary/tags 渲染卡片，
   detail 用于 project.html?id=<id> 详情页。 */
const PROJECTS = [
  {
    id: "todo-list",
    emoji: "📱",
    title: "ToDo 日程壁纸",
    subtitle: "ToDo-list",
    type: "Android 应用",
    language: "Kotlin",
    github: "https://github.com/Litrudy/ToDo-list",
    summary:
      "Android 本地 ToDo + Schedule 锁屏壁纸应用，把每日待办、当前日程和下一事件渲染成可自动更新的个性化壁纸。",
    tags: ["Kotlin", "Jetpack Compose", "Room", "Wallpaper"],
    detail: {
      tagline: "把今天要做的事放到锁屏上",
      overview: [
        "这是一个 Android 本地 ToDo 与日程壁纸应用：用户可以维护每日待办和工作日 / 周末两套日程模板，应用根据当前时间生成锁屏壁纸。",
        "壁纸会展示当前时间段、下一事件和今日未完成 ToDo，并支持内置背景或本地图片背景。应用会分析图片明暗与纹理，自动调整文字颜色、遮罩强度和排版位置。",
        "项目针对 OriginOS 等系统限制做了尽力更新策略：打开 App、修改日程、修改 ToDo、手机重启或到达日程边界时都会尝试校正壁纸。",
      ],
      features: [
        "Room 本地保存每日 ToDo，以及工作日 / 周末两套 Schedule 模板",
        "日程支持新增、编辑、删除和多行批量导入，并校验 24 小时制与重叠时间段",
        "根据日期和当前时间计算当前事件、下一事件和下一次壁纸更新时间",
        "内置六套壁纸，也可选择本地图片作为背景",
        "自动分析图片明暗和纹理，动态调整遮罩、文字颜色与正文位置",
        "使用 AlarmManager 尝试在日程边界刷新壁纸，同时在 App 打开和系统事件中补偿校正",
      ],
      techStack: ["Kotlin", "Jetpack Compose", "Room", "AlarmManager", "Android Wallpaper"],
      note: "2026-06-29 新增到 GitHub 的 Android 小工具项目。",
    },
  },
  {
    id: "desktop-pet",
    emoji: "🖥️",
    title: "桌面宠物",
    subtitle: "DesktopPet",
    type: "Windows 桌面应用",
    language: "Python",
    github: "https://github.com/Litrudy/DesktopPet",
    summary:
      "用 Python 3.12 和 PySide6 制作的 Windows 透明桌面宠物，支持多宠物模型包、托盘菜单、双语界面和开机自启。",
    tags: ["Python", "PySide6", "Windows", "PyInstaller"],
    detail: {
      tagline: "可切换模型包的透明桌面宠物",
      overview: [
        "DesktopPet 是一个 Windows 10/11 桌面宠物应用，窗口透明、无边框、始终置顶，并通过 Qt 工具窗口隐藏任务栏入口。",
        "项目把宠物资源拆成可替换的本地模型包，每个模型可以拥有自己的精灵图、元数据、默认行为参数和中英文对话文件。目前包含小鲨鱼、萨摩耶和英短猫。",
        "应用围绕共享状态机驱动行为，覆盖闲置、行走、睡觉、开心、说话、拖拽和返回等状态，并提供设置窗口、右键菜单与系统托盘入口。",
      ],
      features: [
        "透明无边框置顶窗口，支持多显示器移动范围和气泡位置计算",
        "宠物模型包可切换，资源清单和中英文对话文件按模型独立维护",
        "自动左右翻转移动帧，缺失动作或帧时使用透明占位兜底",
        "支持点击、拖拽、睡觉、说话、闲置反应，以及安静模式和暂停模式",
        "设置中可调整语言、缩放、移动速度和开机启动",
        "测试覆盖配置恢复、资源扫描、状态切换、边界移动和气泡定位等核心逻辑",
      ],
      techStack: ["Python 3.12", "PySide6", "pytest", "PyInstaller", "Windows 10/11"],
      note: "2026-06-29 新增到 GitHub 的桌面应用项目。",
    },
  },
  {
    id: "freetown-port-intro",
    emoji: "⚓",
    title: "弗里敦港沉浸式介绍页",
    subtitle: "freetown-port-intro",
    type: "静态网页 · 物流介绍",
    language: "HTML",
    github: "https://github.com/Litrudy/freetown-port-intro",
    live: "https://litrudy.github.io/freetown-port-intro/",
    summary:
      "以深色电影感和滚动叙事呈现塞拉利昂弗里敦港物流实务，包含 WebGL 背景、视差图片、中英切换和静态部署。",
    tags: ["HTML", "CSS", "JavaScript", "GSAP"],
    detail: {
      tagline: "弗里敦港物流实务的滚动叙事网页",
      overview: [
        "这是一个面向弗里敦港物流介绍的沉浸式静态页面，视觉参考偏深色电影感的滚动叙事风格，用左图右文、视差和区块转场组织信息。",
        "项目采用原生 HTML / CSS / JS 单文件页面，本地 vendored 动效库，无构建步骤，可直接作为 GitHub Pages 静态站点部署。",
        "页面同时考虑性能和可访问性：图片本地自托管并使用 WebP 主图与 JPG 兜底，触摸设备与减少动效偏好下会自动降级强动效。",
      ],
      features: [
        "Lenis 惯性滚动与 GSAP / ScrollTrigger 统一编排动效",
        "标题遮罩揭示、段落错峰入场、数字 count-up 和标签动画",
        "左侧图片滚动视差，并用 clip-path 做擦除式换图",
        "原生 WebGL shader 生成 hero 流体噪点背景",
        "支持中 / 英语言切换，以及自定义磁吸光标",
        "图片自托管，部署目录可通过 git subtree 发布到 gh-pages 分支",
      ],
      techStack: ["HTML5", "CSS", "JavaScript", "GSAP", "ScrollTrigger", "Lenis", "WebGL"],
    },
  },
  {
    id: "combine-dao",
    emoji: "🗡️",
    title: "合道",
    subtitle: "combine-dao",
    type: "独立游戏",
    language: "GDScript",
    stars: 3,
    github: "https://github.com/Litrudy/combine-dao",
    summary:
      "用 Godot 4 制作的修仙题材 Roguelite 动作游戏。在一局局探索中突破境界、构筑流派、收集机缘，与怪物和召唤物同场厮杀。",
    tags: ["Godot 4", "GDScript", "Roguelite", "动作游戏"],
    detail: {
      tagline: "一款修仙题材的 Roguelite 动作游戏",
      overview: [
        "《合道》是我用 Godot 4 引擎独立开发的修仙题材 Roguelite 游戏。玩家在随机生成的地图中探索、战斗、突破境界，每一局都是一次全新的构筑与冒险。",
        "项目从核心战斗循环起步，逐步加入了召唤物、机缘事件、构筑系统，以及随机布置的怪物与事件，目标是把「修仙」的成长感和 Roguelite 的随机性结合起来。",
      ],
      features: [
        "境界突破：通过战斗积累修为，在关键节点突破境界，解锁更强的能力",
        "构筑系统：可视化构筑面板实时预览数值，每局自由搭配出不同流派",
        "机缘事件：风险与收益并存的随机事件，不同选择会改变整局走向",
        "召唤物：可召唤的战斗单位，具备自动寻敌范围与跟随主人的逻辑",
        "智能怪物：怪物拥有警戒范围、脱战机制与随机布置，战斗更有张力",
        "地图交互：可探索的地图事件与互动点",
      ],
      controls: "WASD 移动 · 左键 攻击 · 空格 闪避 · R 突破 · Q / E / F 技能 · Tab 构筑面板",
      techStack: ["Godot 4.6", "GDScript", "Jolt Physics", "D3D12 / GL Compatibility"],
      note: "持续开发中的个人独立游戏项目。",
    },
  },
  {
    id: "vessel-operations-desk",
    emoji: "🚢",
    title: "船舶动态与卸货跟踪系统",
    subtitle: "Vessel Operations Desk",
    type: "全栈 · 行业工具",
    language: "Python · TypeScript",
    github: "https://github.com/Litrudy/vessel-operations-desk",
    summary:
      "为船舶代理日常作业打造的本地化管理系统，覆盖船舶档案、航次、动态事件与卸货进度跟踪。数据全部留在本机，不上云。",
    tags: ["FastAPI", "React", "TypeScript", "SQLite"],
    detail: {
      tagline: "船舶代理的本地化作业台 · v0.4.1",
      overview: [
        "这是一套服务于船舶代理日常工作的管理系统，用来管理船舶航次、ETA、靠泊离港、动态事件和卸货进度。",
        "系统完全在本地运行，所有业务数据仅保存在本机，不连接任何云端服务、不上传文件——这是航运代理场景下对数据安全的硬性要求。",
        "项目按阶段迭代，目前推进到第四阶段（v0.4.1），数据库经历了 7 个版本的无损升级。",
      ],
      features: [
        "船舶与航次管理：档案、11 种状态的航次状态机、搜索筛选分页、软停用不物理删除",
        "动态事件记录：15 种常用事件类型，区分实际发生时间与系统记录时间，可联动航次关键时间",
        "卸货进度跟踪：重量 / 件数 / 车辆三指标独立核算，多货舱批次、累计与完成率实时计算",
        "纠错与审计：直接修改与整批冲销两种方式，全程留存修改历史与原因，进度记录不提供删除",
        "并发安全：乐观并发版本控制，冲突显式报错而非静默覆盖；超计划需二次确认",
        "数据库无损升级：v1 → v7 逐版迁移，旧库可平滑升级",
      ],
      techStack: [
        "Python 3.11 / FastAPI",
        "SQLAlchemy 2.x",
        "SQLite",
        "React / TypeScript / Vite",
        "React Router / Axios",
        "pytest",
      ],
      note: "数据本地保存 · 不上云 · 不集成统计 SDK。",
    },
  },
  {
    id: "work",
    emoji: "🧾",
    title: "船代发票生成系统",
    subtitle: "Invoice Generator",
    type: "全栈 · 行业工具",
    language: "Python · TypeScript",
    github: "https://github.com/Litrudy/work",
    summary:
      "上传一份 Data Excel，自动按行生成几内亚或尼日利亚格式的船代发票并下载。把繁琐的手工填表变成一键生成。",
    tags: ["FastAPI", "Next.js", "openpyxl", "Excel"],
    detail: {
      tagline: "一份 Excel，一键生成合规发票",
      overview: [
        "这是一个把船代发票制作流程自动化的工具：用户上传包含 Data 工作表的 Excel，系统按数据行自动生成几内亚或尼日利亚格式的发票，并打包下载。",
        "发票格式背后有大量业务规则——不同的车辆数、货物数、免税标志会选用不同模板，金额要换算成法语或英语大写文字，还要处理 DA 自动编号、Trans 平移、Minimum 兜底等边界情况。这些规则全部由后端用 Python 精确计算，不依赖 Excel 公式缓存。",
      ],
      features: [
        "智能模板选择：依据 Data 各列自动匹配 General、Vehicle、V&G、bulk、Minimum 等模板",
        "金额文字化：法语（GNF）与英语（NGN）金额大写转换，sentence case 格式",
        "DA 自动编号：每次生成从 0001 起按 Sheet 递增，Trans 平移单独占号，汇总表不参与",
        "免税与税额处理：免税清税与蓝标，Minimum 兜底（低于阈值强制切换）",
        "本机 / 局域网两种部署：可单机使用，也可后端监听全网卡供局域网多机访问",
        "生成日志：每次生成写入金额计算明细与判断过程，便于核对",
      ],
      techStack: ["Python 3.11 / FastAPI", "openpyxl", "Next.js / React", "TypeScript", "Uvicorn"],
    },
  },
  {
    id: "akita",
    emoji: "🌐",
    title: "秋田集团官网",
    subtitle: "Akita Group",
    type: "静态网站 · 多语言",
    language: "HTML · CSS · JS",
    github: "https://github.com/Litrudy/akita",
    live: "https://litrudy.github.io/akita/",
    summary:
      "为物流集团打造的纯静态多页官网，支持中 / 英 / 法三语切换和亮暗双主题，无框架、无构建步骤，开箱即用。",
    tags: ["HTML", "CSS", "JavaScript", "i18n"],
    detail: {
      tagline: "三语 · 双主题 · 零依赖的企业官网",
      overview: [
        "Akita Group（秋田集团）的官方网站，是一个纯静态的多页站点——只有 HTML / CSS / JS，没有框架、没有构建步骤，双击 index.html 就能预览，已部署在 GitHub Pages 上。",
        "全站 7 个页面覆盖首页、关于、服务、运营、案例、新闻和联系，内容以官方文档为准。",
      ],
      features: [
        "三语切换：英文写在标签内，法文 / 中文放 data 属性，JS 自动切换并记忆选择",
        "亮 / 暗双主题：海军蓝 ↔ 炭黑，跟随系统偏好并记忆",
        "7 个完整页面：首页航线图、九国港口网络、服务详情、案例画廊、三语新闻、结构化询价表单",
        "响应式导航：7 项主导航 + 悬停二级菜单，窄屏折叠为汉堡菜单",
        "克制的动效：滚动渐入、数字计数、航线流动，全部尊重 prefers-reduced-motion",
        "设计系统：颜色集中在 CSS 变量，改两个变量即可整站换色",
      ],
      techStack: ["HTML5", "CSS（变量驱动设计系统）", "原生 JavaScript", "GitHub Pages"],
    },
  },
  {
    id: "time-zone-coordinator",
    emoji: "🕐",
    title: "时差协调器",
    subtitle: "Time Zone Coordinator",
    type: "桌面应用 · 小工具",
    language: "Python",
    github: "https://github.com/Litrudy/time-zone-coordinator",
    summary:
      "用 Python 标准库写的 Windows 桌面时差挂件，常驻置顶显示多地时间，支持三套主题、桌面宠物和开机自启。",
    tags: ["Python", "tkinter", "zoneinfo", "Windows"],
    detail: {
      tagline: "桌面上的多时区小挂件",
      overview: [
        "一个常驻桌面的时差小挂件，专为跨地区团队、港口业务和海外协作场景而做。无边框、始终置顶，实时显示目标地区的时间、日期和与本地的真实 UTC 时差。",
        "整个挂件只用 Python 标准库实现（tkinter + zoneinfo + winreg），可以用 PyInstaller 打包成单个 exe 直接分发。",
      ],
      features: [
        "多时区显示：内置 23 个常见城市与港口时区，用 zoneinfo 正确处理夏令时",
        "三套主题：春日 / 机械 / 霓虹，顶部即时切换并记住选择",
        "桌面宠物：英短猫 / 三花猫 / 萨摩耶，移动、睡觉、打招呼三组四帧精灵动画",
        "自由缩放：无边框窗口可从四边四角拖动调整，记忆位置与尺寸",
        "高 DPI 与多显示器：按 96 DPI 逻辑像素保存，跨屏自动换算保持一致视觉尺寸",
        "开机自启：一键设置当前用户开机启动；配置存于 %APPDATA%",
      ],
      techStack: ["Python 3.9+", "tkinter（GUI）", "zoneinfo（时区）", "winreg（自启）", "PyInstaller（打包）"],
    },
  },
  {
    id: "homepage",
    emoji: "🚀",
    title: "我的个人主页",
    subtitle: "homepage",
    type: "个人网站",
    language: "HTML · CSS · JS",
    github: "https://github.com/Litrudy/homepage",
    live: "https://litrudy.github.io/homepage/",
    summary:
      "就是你正在看的这个网站。纯手写 HTML / CSS / JS，练习响应式布局、动画与数据驱动的多页结构。",
    tags: ["HTML", "CSS", "JavaScript"],
    detail: {
      tagline: "你正在浏览的这个网站本身",
      overview: [
        "这个网站没有用任何框架，纯手写 HTML / CSS / JS，用来练习响应式布局、滚动动画、亮暗主题，以及数据驱动的多页结构。",
        "项目与详情页共用同一份数据：主页渲染项目卡片，点进去由同一个模板渲染详情，新增项目只改数据、不碰模板。",
      ],
      features: [
        "数据驱动渲染：项目卡片与详情页都来自一份 data.js",
        "亮 / 暗主题：在 head 内联应用，刷新无闪烁",
        "滚动渐入与导航高亮：IntersectionObserver 实现，错峰入场",
        "移动端汉堡菜单与响应式布局",
        "无障碍：尊重 prefers-reduced-motion，键盘焦点可见",
      ],
      techStack: ["HTML5", "CSS", "原生 JavaScript", "GitHub Pages"],
    },
  },
];
